# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install myst-parser
      - pip install sphinx-rtd-theme
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
